spring.application.name=employee-management-api

# ========================================
# DATABASE - MySQL
# ========================================
# CONEXIÓN CON VERSIONES RECIENTES
spring.datasource.url=jdbc:mysql://localhost:3306/bd_employee_management?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=jara
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========================================
# HIKARI CONNECTION POOL- PERMITE MANTENER UN CONJUNTO DE CONEXIONES REUTILIZABLES Y NO CREAR UNA NUEVA
# ========================================
spring.datasource.hikari.maximum-pool-size=10

# ========================================
# JPA / HIBERNATE
# ========================================
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.database=MYSQL

# ========================================
# SERVER
# ========================================
server.port=8080